# default_language_version:
#     python: python3.7
repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.15
    hooks:
    - id: ruff-check
    - id: ruff-format

-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
    - id: validate-pyproject

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.23.0
    hooks:
    - id: pyproject-fmt
